vim.cmd([[language en_US]])

require("thomas.plugins-setup")
require("thomas.core.options")
require("thomas.core.keymaps")
require("thomas.core.colorscheme")
require("thomas.plugins.comment")
require("thomas.plugins.nvim-tree")
require("thomas.plugins.lualine")
require("thomas.plugins.telescope")
